### PR TITLE
More query options 64

### LINKED ISSUE #64: add more query options to access-module
@MadsJensen requested "Comments", but many others possible too. Requires writing POST-calls using the `_send_request`-method under: `stormdb.access.Query`

- [x] Subject comments
- [x] Study comments

### PR DESCRIPTION
**Pull request by cjayb**
ready for testing/review @MadsJensen @britta-wstnr 

Closes #64

### CODE REVIEW

**Comment by cjayb** [comment]
Gets all meta at once, smacks into a dict. Usage:

```python
from stormdb.access import Query
qy=Query('MEG_service')
info = qy.get_study_info('0006', '20121107')
```

**Comment by cjayb** [comment]
@MadsJensen ready for merge?

**Comment by MadsJensen** [comment]
I get an error if there is a none ASCII character in the comment field, e.g. 'æ'.

**Comment by cjayb** [comment]
Weird, works for me... What's the error you get precisely?

```python
In [1]: from stormdb.access import Query
In [2]: qy = Query('MEG_service')
In [6]: foo=qy.get_study_info('0001', '20111123_000000')

In [7]: foo
Out[7]:
{'studyTime': '2011-11-23 00:00:00',
 'excluded': '0',
 'excludedCategory': '',
 'excludedReason': '',
 'comments': 'Study comments have æøå'}

In [8]: foo['comments']
Out[8]: 'Study comments have æøå'
```

**Comment by cjayb** [comment]
Reopen as issue if still problem

**Pull request merged**
